- zbarcommand:
    Linux: "zbarcam /dev/video0"
    Windows: C:\Program Files\ZBar\bin\zbarcam

- schedule:
    age: klein
    path: data/klein_2017.csv
- schedule:
    age: groot
    path: data/groot_2017.csv
- leiding_schedule:
    path_zaterdag: "data/Leidingplanning 2017 date formatted zaterdag.xlsx"
    path_zondag: "data/Leidingplanning 2017 date formatted zondag.xlsx"

- activity:
    name: "scotland yard"
    image: images/scotlandyard.gif
    sound: sounds/scotlandyard.mp3
- activity:
    name: "lange afstand drinken"
    image: images/drinken.gif
    sound: sounds/drinken.mp3
- activity:
    name: pubquiz
    image: images/pubquiz.gif
    sound: sounds/pubquiz.mp3
- activity:
    name: voetbal
    image: images/voetbal.gif
    sound: sounds/voetbal.mp3
- activity:
    name: ballon
    image: images/ballon.gif
    sound: sounds/ballon.mp3
- activity:
    name: inloopspellen
    image: images/inloop.gif
    sound: sounds/inloopspellen.mp3
- activity:
    name: drinken
    image: images/drinken.gif
    sound: sounds/drinken.mp3
- activity:
    name: creatief
    image: images/creative.gif
    sound: sounds/creatief.mp3
- activity:
    name: gps
    image: images/gps.gif
    sound: sounds/gps.mp3
- activity:
    name: parcours
    image: images/parcours.gif
    sound: sounds/parcours.mp3
- activity:
    name: jota
    image: images/jota.gif
    sound: sounds/jota.mp3
- activity:
    name: joti
    image: images/joti.gif
    sound: sounds/joti.mp3
- activity:
    name: radio
    image: images/radio.gif
    sound: sounds/radio.mp3
- activity:
    name: avondeten
    image: images/avondeten.gif
    sound: sounds/avondeten.mp3
- activity:
    name: avondspel
    image: images/avondspel.gif
    sound: sounds/avondspel.mp3
- activity:
    name: bos
    image: images/bos.gif
    sound: sounds/bos.mp3
- activity:
    name: bosspel
    image: images/bos.gif
    sound: sounds/bos.mp3
- activity:
    name: 'gezamenlijk spel'
    image: 'images/gezamenlijk spel.gif'
    sound: 'sounds/gezamenlijk spel.mp3'
- activity:
    name: 'gezamenlijk programma'
    image: 'images/gezamenlijk spel.gif'
    sound: 'sounds/gezamenlijk spel.mp3'
- activity:
    name: hunt
    image: images/hunt.gif
    sound: sounds/hunt.mp3
- activity:
    name: lunch
    image: images/lunch.gif
    sound: sounds/lunch.mp3
- activity:
    name: ontbijt
    image: images/ontbijt.gif
    sound: sounds/ontbijt.mp3
- activity:
    name: opening
    image: images/opening.gif
    sound: sounds/opening.mp3
- activity:
    name:  'opstaan en spullen opruimen'
    image: 'images/opstaan en spullen opruimen.gif'
    sound: 'sounds/opstaan en spullen opruimen.mp3'
- activity:
    name: slapen
    image: images/slapen.gif
    sound: sounds/slapen.mp3
- activity:
    name: sluiting
    image: images/sluiting.gif
    sound: sounds/sluiting.mp3
- activity:
    name: 'tenten opzetten'
    image: 'images/tenten opzetten.GIF'
    sound: 'sounds/tenten opzetten.mp3'
- activity:
    name: "tocht van hier naar daar"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: "tocht van daar naar hier"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: tocht
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: "tocht naar hier"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: "tocht naar ginder"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: "tocht van ginder naar hier"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: "tocht van hier naar ginder"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: tv
    image: images/tv.gif
    sound: sounds/tv.mp3
- activity:
    name: veld
    image: images/veld.gif
    sound: sounds/veld.mp3
- activity:
    name:  'wassen, plassen en naar bed'
    image: 'images/wassen, plassen en naar bed.gif'
    sound: 'sounds/wassen, plassen en naar bed.mp3'
- activity: 
    name: 'survival'
    image: 'images/survival.gif'
- activity: 
    name: 'reuze ballen'
    image: 'images/reuze ballen.gif'
- activity: 
    name: 'geheimschrift'
    image: 'images/geheimschrift.gif'
- activity: 
    name: 'sherow programma'
    image: 'images/sherrow programma.gif'
- activity: 
    name: 'levend mijnenvegen'
    image: 'images/levend mijnenveger.gif'
- activity: 
    name: 'uitleg + klaarmaken voor the hunt'
    image: images/hunt.gif
- activity:
    name: 'levend memorie'
    image: 'images/memory.gif'
- activity:
    name: 'blinde geleide spel'
    image: 'images/blindegeleidespel.gif'
- activity:
    name: 'levend kwartet'
    image: 'images/kwartet.gif'
- activity:
    name: 'de grote ontknoping'
    image: 'images/grote ontknoping.gif'
- activity:
    name: 'kettingreactie'
    image: 'images/kettingreactie.gif'
- activity:
    name: 'boerengolf'
    image: 'images/boerengolf.gif'
- activity:
    name: 'eggdrop'
    image: 'images/eggdrop.gif'
- activity:
    name: 'kampvuur'
    image: 'images/kampvuur.gif'
- activity:
    name: 'klaarmaken voor the hunt'
    image: 'images/hunt.gif'
- activity:
    name: 'flessenspel'
    image: 'images/flessenspel.gif'
- activity:
    name: 'moment met eigen speltak'
    image: 'images/Brilsmurf.gif'
- activity:
    name: 'naar huis'
    image: 'images/huis.gif'
- activity:
    name:  'opstaan + spullen opruimen'
    image: 'images/opstaan en spullen opruimen.gif'
    sound: 'sounds/opstaan en spullen opruimen.mp3'
- activity:
    name:  'opstaan'
    image: 'images/opstaan en spullen opruimen.gif'
    sound: 'sounds/opstaan en spullen opruimen.mp3'
- activity:
    name: 'tangram'
    image: 'images/tangram.gif'
- activity:
    name: 'the phone'
    image: 'images/phone.gif'
- activity:
    name: 'ticket-activiteit ronde 1'
    image: 'images/ticket.gif'
- activity:
    name: 'ticket-activiteit ronde 2'
    image: 'images/ticket.gif'
- activity:
    name: 'walkie-talkie'
    image: 'images/walkietalkie.gif' #TODO add
- activity:
    name: 'leipe halli galli'
    image: 'images/halli_galli.gif'
- activity:
    name: 'muizen vissen'
    image: 'images/muizen.gif'
- activity:
    name: 'escape-room'
    image: 'images/escape-room.gif'
- activity:
    name: 'stormbaan'
    image: 'images/stormbaan.gif'
- activity:
    name: 'ticket-activiteit ronde 1'
    image: 'images/ticket.gif'
- activity:
    name: 'ticket-activiteit ronde 2'
    image: 'images/ticket.gif'
- activity:
    name: 'levend halli galli'
    image: 'images/halli_galli.gif'
- activity:
    name: 'levend zeeslag'
    image: 'images/zeeslag.gif'
- activity:
    name: 'vossenjacht'
    image: 'images/share.png'
- activity:
    name: 'proefjes'
    image: 'images/proefjes.jpg'
- activity:
    name: 'stratego'
    image: 'images/stratego.jpg'
- activity:
    name: 'pokemon-go'
    image: 'images/pokemongo.png'
- activity:
    name: 'doordraai'
    image: 'images/doordraai.png'
- activity:
    name: 'langeafstandspionieren'
    image: 'images/walkietalkie.gif'
- activity:
    name: 'hoverballshooting'
    image: 'images/hunt.gif'
- activity:
    name: 'vlaggen'
    image: 'images/flag.jpg'
- activity:
    name: 'cluedo'
    image: 'images/cluedo.jpg'
- activity:
    name: 'gps-doolhof'
    image: 'images/geocache.png'
- activity:
    name: 'ginder-tinder'
    image: 'images/gindertinder.jpg'
- activity:
    name: 'highland-games'
    image: 'images/highlandgames.jpg'
- activity:
    name: 'instagramspel'
    image: 'images/instagram.jpg'
- activity:
    name: 'kubb'
    image: 'images/kubb.jpg'
- activity:
    name: "de lama's"
    image: 'images/lamas.png'
- activity:
    name: 'washandjesmonsterspel'
    image: 'images/monster.jpg'
- activity:
    name: 'radio actieve vaten'
    image: 'images/radio_actieve_vaten.jpg'
- activity:
    name: 'saboteur'
    image: 'images/saboteur.jpg'
- activity:
    name: 'solderen'
    image: 'images/solderen.jpg'
- activity:
    name: 'station'
    image: 'images/station.png'
- activity:
    name: 'parcours'
    image: 'images/tetris.png'
- activity:
    name: 'communicatie-estafette'
    image: 'images/tin-can-telephone.jpg'
- activity:
    name: 'water spons vuur'
    image: 'images/water_spons_vuur.jpg'
- activity:
    name: 'workshop 1'
    image: 'images/workshop.png'
- activity:
    name: 'workshop 2'
    image: 'images/workshop.png'
- activity:
    name: 'workshop 3'
    image: 'images/workshop.png'
- activity:
    name: 'octopus'
    image: 'images/octopus.jpg'
- activity:
    name: 'elektronica slopen/knutselen'
    image: 'images/elektronica.png'
- activity:
    name: 'jongens tegen de meisjes'
    image: 'images/jongens_tegen_meisjes.png'
- activity:
    name: 'lunch + tickets workshops'
    image: images/lunch.gif
- activity:
    name: 'opbouw+voorbereiden'
    image: images/werk-in-uitvoering.jpg
- activity:
    name: 'bevers'
    image: images/bevers.png


- timeformat: "%d-%m-%Y %H:%M"

