- schedule:
    age: klein
    path: data/prog_klein.csv
- schedule: 
    age: groot
    path: data/prog_groot.csv

- activity:
    name: jota
    image: images/jota.gif
    sound: sounds/jota.mp3
- activity:
    name: joti
    image: images/joti.jpg
    sound: sounds/joti.mp3
- activity:
    name: radio
    image: images/radio.png
    sound: sounds/radio.mp3

- timeformat: "%d/%m/%y %H:%M"
