- zbarcommand: "zbarcam"# /dev/video1"

- schedule:
    age: klein
    path: data/planning_2013_klein.csv
- schedule: 
    age: groot
    path: data/planning_2013_groot.csv

- activity:
    name: "scotland yard"
    image: images/scotlandyard.jpg
    sound: sounds/scotlandyard.mp3
- activity:
    name: "lange afstand drinken"
    image: images/drinken.jpg
    sound: sounds/drinken.mp3
- activity:
    name: pubquiz
    image: images/pubquiz.jpg
    sound: sounds/pubquiz.mp3
- activity:
    name: voetbal
    image: images/voetbal.jpg
    sound: sounds/voetbal.mp3
- activity:
    name: ballon
    image: images/ballon.gif
    sound: sounds/ballon.mp3
- activity:
    name: inloopspellen
    image: images/inloop.jpg
    sound: sounds/inloopspellen.mp3
- activity:
    name: drinken
    image: images/drinken.jpg
    sound: sounds/drinken.mp3
- activity:
    name: creatief
    image: images/creative.jpg
    sound: sounds/creatief.mp3
- activity:
    name: gps
    image: images/gps.png
    sound: sounds/gps.mp3
- activity:
    name: parcours
    image: images/parcours.jpg
    sound: sounds/parcours.mp3
- activity:
    name: jota
    image: images/jota.gif
    sound: sounds/jota.mp3
- activity:
    name: joti
    image: images/joti.jpg
    sound: sounds/joti.mp3
- activity:
    name: radio
    image: images/radio.png
    sound: sounds/radio.mp3
- activity:
    name: avondeten
    image: images/avondeten.png
    sound: sounds/avondeten.mp3
- activity:
    name: avondspel
    image: images/avondspel.png
    sound: sounds/avondspel.mp3
- activity:
    name: bos
    image: images/bos.png
    sound: sounds/bos.mp3
- activity:
    name: bosspel
    image: images/bos.png
    sound: sounds/bos.mp3
- activity:
    name: 'gezamenlijk spel'
    image: 'images/gezamenlijk spel.jpg'
    sound: 'sounds/gezamenlijk spel.mp3'
- activity:
    name: 'gezamenlijk programma'
    image: 'images/gezamenlijk spel.jpg'
    sound: 'sounds/gezamenlijk spel.mp3'
- activity:
    name: hunt
    image: images/hunt.jpg
    sound: sounds/hunt.mp3
- activity:
    name: lunch
    image: images/lunch.jpg
    sound: sounds/lunch.mp3
- activity:
    name: ontbijt
    image: images/ontbijt.jpg
    sound: sounds/ontbijt.mp3
- activity:
    name: opening
    image: images/opening.jpg
    sound: sounds/opening.mp3
- activity:
    name:  'opstaan en spullen opruimen'
    image: 'images/opstaan en spullen opruimen.jpg'
    sound: 'sounds/opstaan en spullen opruimen.mp3'
- activity:
    name: slapen
    image: images/slapen.jpg
    sound: sounds/slapen.mp3
- activity:
    name: sluiting
    image: images/sluiting.jpg
    sound: sounds/sluiting.mp3
- activity:
    name: 'tenten opzetten'
    image: 'images/tenten opzetten.GIF'
    sound: 'sounds/tenten opzetten.mp3'
- activity:
    name: 'images/tocht van daar naar hier'
    image: 'images/tocht van daar naar hier.gif'
    sound: 'sounds/tocht van daar naar hier.mp3'
- activity:
    name: "tocht van hier naar daar"
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: tocht
    image: 'images/tocht van hier naar daar.gif'
    sound: 'sounds/tocht van hier naar daar.mp3'
- activity:
    name: tv
    image: images/tv.gif
    sound: sounds/tv.mp3
- activity:
    name: veld
    image: images/veld.gif
    sound: sounds/veld.mp3
- activity:
    name:  'wassen, plassen en naar bed'
    image: 'images/wassen, plassen en naar bed.jpeg'
    sound: 'sounds/wassen, plassen en naar bed.mp3'
#New:
- activity: 
    name: 'Survival'
    image: 'images/survival.gif'
- activity: 
    name: 'Reuze ballen'
    image: 'images/Reuze ballen.gif'
- activity: 
    name: 'Geheimschrift'
    image: 'images/Geheimschrift.gif'
- activity: 
    name: 'Sherow programma'
    image: 'images/Sherow programma.gif'
- activity: 
    name: 'Levend Mijnenvegen'
    image: 'images/Levend Mijnenvegen.gif'
- activity: 
    name: 'Uitleg + klaarmaken voor the Hunt'
    image: 'images/Uitleg_klaarmaken voor the Hunt.gif'
- activity:
    name: 'Levend memorie'
    image: 'images/Levend memorie.gif'
- activity:
    name: 'Blinde geleide spel'
    image: 'images/Blinde geleide spel.gif'
- activity:
    name: 'Levend kwartet'
    image: 'images/Levend kwartet.gif'
- activity:
    name: 'De grote ontknoping'
    image: 'images/De grote ontknoping.gif'
- activity:
    name: 'Kettingreactie'
    image: 'images/Kettingreactie.gif'



- timeformat: "%d-%m-%Y %H:%M"

